version:  "3.8"
services:
  db:
    image: postgres
    container_name: bank_system
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_system
    ports:
      - "5432:5432"