spring:
  application:
    name: redis-java
  datasource:
    url: jdbc:postgresql://45.89.65.77:5432/redisDemo
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis